---
title: "My Presentation"
author: "Joel Nitta"
format:
  revealjs:
    incremental: false
    css: styles.css
execute: 
  echo: true
---

## 自己紹介：ニッタ ジョエル

- 千葉大学 准教授
- シダ植物の進化や生態学
- Rパッケージ開発（進化生態学系）

## Quarto

- QuartoはRやPythonの計算結果を直接文章に入れるツール
  - 使い方が非常に多様で豊富

- 「文章」には様々な形式が含まれいています
  - HTML
  - PDF
  - スライド
  - ウエブサイト

## Quartoの多言語機能

- しかし、Quartoは比較的新しいため、欠けている機能もあります。

- 備え付けで多言語できる機能がありません

https://github.com/quarto-dev/quarto-cli/issues/275

# caution

- this functionality may eventually be added to Quarto, which would make this package obsolete

- but we don't know their timeline, so if you need i18n now, it's a good option (though not the only one)

## babelquarto

- translate website or book

- simple file structure

- any number of languages

- An R package, not a plugin (may not be compatible with all plugins)

## babelquarto demo using SWC-JA

- index.qmd

- index.ja.qmd

## register language

- modifies _quarto.yml

## profiles

- Use for more complex setups

# Local rendering

- render function

- httw function

## github action

- modified from default, needs to install r packages

## what about translating content?

- chatgpt custom gpt

- babeldown integration with deepl

## what about keeping translation up to date?

- local gettext and PO files

- web based apps like crowdin

## take home message

- i18n enbles access and grows communities!
